CTSRD-CHERI/cheribsd-ports

devel/llvm/Makefile

~~Update the llvm-cheri and llvm-morello ports to the latest toolchains and~~ update devel/llvm to link to those ports by default on appropriate architectures.

CHERI LLVM updates

---

Mk/Uses/linux.mk

CheriBSD does not support Linux compatibility yet. When building packages, we shouldn't waste time processing Linux ports.

Disable Linux ports

---

Mk/Scripts/do-depends.sh
Mk/Uses/cmake.mk
Mk/Uses/python.mk
Mk/bsd.commands.mk
Mk/bsd.options.mk
Mk/bsd.port.mk
devel/autoconf/Makefile
devel/automake/Makefile
devel/cmake/Makefile
devel/meson/Makefile
devel/ninja/Makefile
lang/python39/Makefile

This PR allows to install port dependencies from a remote package repository when the following variables are set:
```
USE_PACKAGE_DEPENDS=1
USE_PACKAGE_DEPENDS_REMOTE=1
```
It also allows to install port dependencies that aren't adapted to CheriABI yet, and are marked using `USE_PKG64=1` in their Makefiles, using pkg64 if the following variable is set:
```
USE_PACKAGE_64_DEPENDS_ONLY=1
```
At the moment, autoconf, automake, cmake, meson, ninja, python39 (the default Python) and all Python ports installed in the site-packages tree are marked as allowed to be installed with pkg64.

Allow to install port dependencies using package managers

---

Mk/Uses/python.mk

In a poudriere jail the script ports_env.sh sets the environmental varaible PYTHONBASE. In a CheriABI jail this should be set to the LOCALBASE64 (as a CheriABI Python package is currently not available). Once the value of PYTHONBASE is set in /etc/make.conf.ports_env it is never updated to the correct value in python.mk.

Use LOCALBASE64 not LOCALBASE to set the default PYTHONBASE.

---

x11-servers/xwayland-devel/Makefile
x11-toolkits/libXt/Makefile
x11-toolkits/libXt/distinfo
x11-wm/plasma5-kwin/Makefile
x11/libX11/Makefile
x11/libX11/distinfo
x11/libXrender/files/cheribsd.patch
x11/plasma5-plasma-workspace/Makefile
x11/plasma5-plasma-workspace/files/cheribsd.patch
x11/plasma5-plasma-workspace/files/patch-setup_xdg_environment

With these changes `dbus-run-session startplasma-wayland` (with the existing chmod hack due to a lack of proper seat management, since ConsoleKit requires GLib) can be used instead of the hacky minimal manual approach used before.

Fix startplasma-wayland

---

x11/plasma5-kactivitymanagerd/Makefile

In a full KDE desktop qt5-sqldrivers-sqlite3 normally ends up being pulled in via a long chain of dependencies to qt5-help, which has it as an explicit dependency. However, in more minimal environments, we can end up with the package being missing, which causes kactivitymanagerd to immediately exit with a fatal error from being unable to open the database. If it exits too quickly this can even cause plasmashell to abort its startup, otherwise it leads to repeated kactivitymanagerd crashes that, by default, get reported by Dr Konqi as a flood of popups.

x11/plasma5-kactivitymanagerd: Add missing USE_QT=sql-sqlite3:run

---

x11-wm/plasma5-kwin/files/cheribsd.patch

Some of KWin's Wayland interfaces require the binary to be trusted, but the code to do this relies on a Linux-like procfs to be mounted. FreeBSD has linprocfs, so a workaround would be to mount that on FreeBSD, but it's currently tied to Linuxulator bits and doesn't get built on CHERI architectures in CheriBSD. Instead, change the code to use FreeBSD's sysctl equivalent with a slightly ugly patch.
This fixes Task Manager not knowing about any of the open windows, since the org_kde_plasma_window_management_interface interface it uses for that is one of the restricted interfaces, and so it would sit there forever waiting for its plasmaWindowManagementAnnounced callback to be invoked.
Note that in 5.26 KWaylandServer is merged into KWin itself and so we should instead reuse a generalised (to …

x11-wm/plasma5-kwin: Fix trusting processes on linprocfs-less FreeBSD

---

sysutils/seatd/Makefile
sysutils/seatd/files/cpp.patch
sysutils/seatd/files/dri.patch
x11-wm/plasma5-kwin/Makefile
x11-wm/plasma5-kwin/files/cheribsd.patch
x11/cheri-desktop/Makefile
x11/cheri-desktop/files/cheri-desktop
x11/cheri-desktop/files/sddm.in
x11/cheri-desktop/files/seatd.in
x11/cheri-desktop/pkg-plist
x11/sddm/Makefile
x11/sddm/files/cheribsd.patch
x11/sddm/pkg-plist

This adds support for two things:
* So long as a user is in the video group they no longer need to chmod/chown any input devices from root-only in order to be able to run KWin, as they can now access them via seatd
* Users can log in via SDDM rather than logging into a console and running a command to start KDE
The services are also auto-started by default, with a global cheri_desktop_enable="YES/NO" to control them both (or they can be controlled individually too if desired, but users shouldn't do that in case we add to the set of packages later and introduce new things that need enabling for a desktop environment).

SDDM and seatd support

---

textproc/libxml2/Makefile
textproc/libxml2/distinfo

The patches are taken from the merge requests to the libxml2 upstream:
https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/200
https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/202
Closes #70

Updated port with fixes from ctsrd-cheri/libxml2.

---

x11-servers/xorg-server/files/cheribsd.patch
x11-servers/xwayland-devel/files/cheribsd.patch
x11/libXi/files/cheribsd.patch
x11/plasma5-plasma-workspace/files/cheribsd.patch

Plasma (X11) still doesn't work when selected as kwin_x11 times out trying to use GL compositing and restarts itself without compositing, but things no longer core dump so X in general (for things that want to use Xwayland) is likely in better shape than it was. Not sure why X11 compositing isn't working, something about SYNC extension fences never getting triggered from kwin's perspective, but we don't actually need it to work.

Various GUI fixes

---

www/firefox/Makefile
www/firefox/files/cheribsd.patch

Disable implied PROT_MAX and prefer Wayland.
I've compiled these on amd64 and verified the elf flags took, but not tested the results.

Firefox patches

---

Mk/Uses/compiler.mk
devel/autoconf/Makefile
devel/automake/Makefile
devel/cmake-core/Makefile
devel/cmake/Makefile
devel/ninja/Makefile

Work around issues in some top-10 blockers.
Remove incorrect BROKEN entries, work around breakage in a few other cases.
With these changes meson/python will be our biggest blockers followed by go and openjdk.
(Branch contains commits from #81)

Clear build blockers

---

Mk/Scripts/do-depends.sh
Mk/Uses/autoreconf.mk
Mk/Uses/cmake.mk
Mk/Uses/meson.mk
Mk/Uses/perl5.mk
Mk/Uses/python.mk
Mk/bsd.port.mk
devel/gnulib/files/extrapatch-cheribsd-rawmemchr.patch
devel/kf5-ki18n/Makefile
devel/meson/Makefile
devel/py-lxml/Makefile
devel/qt5-qmake/Makefile
devel/yaml-cpp/Makefile
devel/yaml-cpp/pkg-plist
lang/python39/Makefile
textproc/kf5-syntax-highlighting/Makefile
x11-themes/kf5-breeze-icons/Makefile

These changes fix remaining issues to enable GUI stack package building with Poudriere, making use of hybrid ABI utilities. With https://github.com/CTSRD-CHERI/poudriere/pull/1 and this PR, we should be able to build all CherIBSD packages using our Poudriere infrastructure.

Enable GUI stack package building with Poudriere

---

math/gmp/Makefile
math/gmp/files/cheribsd.patch

- Patch configure to use sizeof(long) instead of sizeof(void *) to decide on 32 vs 64-bit ABI for aarch64.
- Disable assembly for purecap ABIs.

math/gmp: Support purecap builds on Morello.

---

devel/llvm-base/files/wrapper.sh.in

Enable `-morello-bounded-memargs=caller-only` for all new purecap builds. See also CTSRD-CHERI/cheribsd#1695.

Switch to new Morello ABI

---

devel/llvm-base/Makefile

Mk/Scripts/actual-package-depends.sh removes a dependency on clang if it is found in $PATH and does not belong to any package.
Since FreeBSD does include clang in the base system and hence it would find it in $PATH as well, change the dependency on clang to use its absolute path rather than a binary name.

devel/llvm-base: depend on the absolute clang path

---

editors/emacs/files/patch-cheribsd-stdint.patch

Add extra definitions to work around the absence of INTMAX_WIDTH, UINTMAX_WIDTH and SIZE_WIDTH from CheriBSD stdint.h
This should resolve #126

Fix emacs hybrid ABI builds.

---

textproc/jade/Makefile

This fixes configure and build on CheriBSD

textproc/jade: remove non-functional deoptimization

---

audio/mpg123/Makefile.purecap
security/gnutls/Makefile.purecap
security/nettle/Makefile.purecap

Get some top blockers working by disabling their assembly bits that don't work with purecap.

Disable unadapted legacy assembly in a few ports

---

devel/Makefile
devel/ghidra-meta/Makefile
devel/ghidra/Makefile

A user trying to explicitly build devel/ghidra will be informed that it's ignored on CheriBSD, similar to https://github.com/CTSRD-CHERI/cheribsd-ports/commit/28e64816f4b4be9b8dd11cedebe5fd517d0d0394.

devel/ghidra-meta: add meta port and ignore devel/ghidra

---

devel/llvm-base/Makefile
devel/llvm-base/files/wrapper.sh.in

The `cc` script will use this flag by default starting with the next CheriBSD release.

c18n: Enable -morello-bounded-memargs for purecap userland

---

devel/distcc/Makefile

By default, distcc does not support preprocessing of headers on remote machines. This can cause bottlenecks when compiling C++ code that makes heavy use of headers for optimization and headers like v8. Add a flavor to distcc that compiles it in pump mode, which allows distcc to offload header processing to remote machines.

devel/distcc: Add a -pump flavor.

---

ports-mgmt/dialog4ports/files/cheribsd.patch

Prevent DLGK_ITEM_NEXT access beyond the bounds of the list. Moving the check forward mirrors the existing patch for the DLGK_ITEM_PREV action.

ports-mgmt/dialog4ports: add the CheriBSD patch

---

lang/go-devel/Makefile
lang/go120/files/cheribsd.patch

Ensure that the MAKE_ENV is respected in go-devel and build go without async preemption. This works around an incompatibility between CheriBSD and the bootstrap Go.

Add patch for CheriBSD freebsd64 Go 1.20.3

---

devel/protobuf/Makefile.purecap
devel/protobuf/files/cheribsd.patch

A set of very explicit changes for CHERI. Some of the changes are required due to the reluctance to provide alignment greater that 8 bytes assumed by ubsan and tcmalloc debug allocation logic.
With these changes the protobuf port compiles but as the package archive does not contain the git submodules the tests cannot be ran.

devel/protobuf: Initial set of cheri fixes

---

devel/glib20/Makefile
devel/glib20/files/cheribsd.patch
net/libslirp/files/cheribsd.patch

This is useful for bhyve, which has a network backend that makes use of libslirp to provide userspace networking. Unfortunately, libslirp requires a smallish patch to work under CHERI. It works in my testing but needs more thought before it can be upstreamed; see the commit log message for some details.
Note, I only tested this by building ports locally on my morello system. I suspect that enabling glib20 for purecap will cause us to start building lots of other packages which previously had been skipped.

Make purecap libslirp available

---

sysutils/cheri-vm-support/Makefile

Install libslirp to enable networking in bhyve.
(cherry picked from commit 1f95e59b714562be86e7f936101d3f4e47d7a54d)

24.05: sysutils/cheri-vm-support: include libslirp

---

Mk/bsd.default-versions.mk
lang/Makefile
lang/go121/Makefile
lang/go121/distinfo
lang/go121/files/cheribsd.patch
lang/go121/files/patch-src_cmd_go_internal_modload_vendor.go

* Cherry-pick go121 from upstream
* Apply the same patches as in #156
* Bump the default go version to 1.21 (matching upstream)

lang/go: Add Go 1.21 port from upstream and bump default version

---

net/libslirp/files/cheribsd.patch

This unbreaks TCP when using libslirp on CheriBSD.

net/libslirp: Fix the layout of struct tcpiphdr

---

accessibility/at-spi2-core/Makefile
accessibility/at-spi2-core/files/cheribsd.patch
accessibility/at-spi2-core/pkg-plist

Initial set of patches for accessibility/at-spi2-core generated from [1].
[1] https://github.com/CTSRD-CHERI/at-spi2-core/tree/fd01d564b5aa69d179f57546f6e4cc5f2ba414fa
Temporarily disable gobject introspection for purecap, until purecap libffi contains the support for closures required by this feature.

[cheriabi] Initial patch for accessibility/at-spi2-core

---

Mk/Uses/go.mk
lang/go121/Makefile
security/boringssl/Makefile
security/boringssl/files/cheribsd.patch

Initial patch for security/boringssl generated from [1].
[1] https://github.com/CTSRD-CHERI/boringssl/tree/53f1fab27782b3941b93968916a92f9dea4936ea
Temporarily disable Go asynchronous preemption in security/boringssl when running go during build and test.
Mk/Uses/go.mk: initial patch to support as build/test dependency
1. Added GO_LOCALBASE conditional set to LOCALBASE64 when a port's USE_GO is set to pkg64 and LOCALBASE otherwise.
2. Added to GODEBUG=asyncpreemptoff=1 to disable asynchronous preemption. Note that this may also be required to be added to a port's MAKE_ENV depending on how Go is used.

security/boringssl: initial patch for CheriABI

---

security/nss/Makefile.purecap
security/nss/files/cheribsd.patch

Initial patch for security/nss generated from [1]:
[1] https://github.com/CTSRD-CHERI/nss/tree/ff79b39ea852b3101997eea1e7652a98772843f9
Removed Makefile.purecap, which marked the port as broken for purecap.

security/nss: initial patch for CheriABI

---

x11-toolkits/gtk30/files/cheribsd.patch

The updated patch changes the use of types in various template files from `gsize` to `GType`. This ensures capability provenance for `gobject` type identifiers.
Updated patch for x11-toolkits/gtk30 generated from [1].
[1] https://github.com/CTSRD-CHERI/gtk/tree/420eb25fe1d3e28fca2327c1ac48dec83cecffd1

x11-toolkits/gtk30: updated patch for CheriABI

---

devel/jsoncpp/files/cheribsd.patch

Apply @jrtc27 's fix from master to the port tree version (1.9.5):
`git cherry-pick -x 42e892d96e47b1f6e29844cc705e148ec4856448`
Initial patch for devel/jsoncpp generated from [1].
[1] https://github.com/CTSRD-CHERI/jsoncpp/tree/5cc9ec8217716e6a129ca93bedc441d7079f4407

devel/jsoncpp: initial patch for CheriABI

---

www/nginx/files/nginx.in

www/nginx: Use ETCDIR substitution for path to config file
